web/config/routes.rb
Rails.application.routes.draw do
  resources :lunch_items

  resources :lunches

  devise_for :users
  resources :bloggs do
    resources :comments
  end

  root 'welcome#index'

end

web/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.role == 'admin';
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

web/app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
  validates :title, presence: true,
            length: { minimum: 5 }
end

web/app/models/blogg.rb
class Blogg < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
            length: { minimum: 5 }
end

web/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :blogg
end

web/app/models/lunch.rb
class Lunch < ActiveRecord::Base
  has_many :lunch_items, :class_name => 'LunchItem', dependent: :destroy
end

web/app/models/lunch_item.rb
class LunchItem < ActiveRecord::Base
  belongs_to :lunch
end

web/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

web/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = exception.message
    redirect_to bloggs_path
  end
end

web/app/controllers/bloggs_controller.rb
class BloggsController < ApplicationController

  before_filter :authenticate_user!, :except => [:index, :show]

  def index
    @articles = Blogg.all
  end

  def show
    @article = Blogg.find(params[:id])
  end

  def new
    @article = Blogg.new
    authorize! :new, @article
  end

  def edit
    puts 'EDITING'
    puts params
    @article = Blogg.find(params[:id])
    authorize! :edit, @article
  end

  def create
    @article = Blogg.new(article_params)
    authorize! :create, @article
    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def update
    @article = Blogg.find(params[:id])
    authorize! :update, @article
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @tempBlog = Blogg.find(params[:id])
    authorize! :destroy, @tempBlog
    @tempBlog.destroy

    redirect_to bloggs_path
  end

  private
  def article_params
    params.require(:blogg).permit(:title, :text)
  end
end

web/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

  def create
    @article = Blogg.find(params[:blogg_id])
    @comment = @article.comments.create(comment_params)
    redirect_to blogg_path(@article)
  end

  def destroy
    @article = Blogg.find(params[:blogg_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to blogg_path(@article)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

web/app/controllers/lunch_items_controller.rb
class LunchItemsController < ApplicationController
  before_action :set_lunch_item, only: [:show, :edit, :update, :destroy]

  # GET /lunch_items
  # GET /lunch_items.json
  def index
    @lunch_items = LunchItem.all
  end

  # GET /lunch_items/1
  # GET /lunch_items/1.json
  def show
  end

  # GET /lunch_items/new
  def new
    @lunch_item = LunchItem.new
  end

  # GET /lunch_items/1/edit
  def edit
  end

  # POST /lunch_items
  # POST /lunch_items.json
  def create
    @lunch_item = LunchItem.new(lunch_item_params)

    respond_to do |format|
      if @lunch_item.save
        format.html { redirect_to @lunch_item, notice: 'Lunch item was successfully created.' }
        format.json { render :show, status: :created, location: @lunch_item }
      else
        format.html { render :new }
        format.json { render json: @lunch_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lunch_items/1
  # PATCH/PUT /lunch_items/1.json
  def update
    respond_to do |format|
      if @lunch_item.update(lunch_item_params)
        format.html { redirect_to @lunch_item, notice: 'Lunch item was successfully updated.' }
        format.json { render :show, status: :ok, location: @lunch_item }
      else
        format.html { render :edit }
        format.json { render json: @lunch_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lunch_items/1
  # DELETE /lunch_items/1.json
  def destroy
    @lunch_item.destroy
    respond_to do |format|
      format.html { redirect_to lunch_items_url, notice: 'Lunch item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lunch_item
      @lunch_item = LunchItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lunch_item_params
      params.require(:lunch_item).permit(:name, :vegetarian, :lunch_id)
    end
end

web/app/controllers/lunches_controller.rb
class LunchesController < ApplicationController
  before_action :set_lunch, only: [:show, :edit, :update, :destroy]

  # GET /lunches
  # GET /lunches.json
  def index
    @lunches = Lunch.all
  end

  # GET /lunches/1
  # GET /lunches/1.json
  def show
  end

  # GET /lunches/new
  def new
    @lunch = Lunch.new
  end

  # GET /lunches/1/edit
  def edit
  end

  # POST /lunches
  # POST /lunches.json
  def create
    @lunch = Lunch.new(lunch_params)

    respond_to do |format|
      if @lunch.save
        format.html { redirect_to @lunch, notice: 'Lunch was successfully created.' }
        format.json { render :show, status: :created, location: @lunch }
      else
        format.html { render :new }
        format.json { render json: @lunch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lunches/1
  # PATCH/PUT /lunches/1.json
  def update
    respond_to do |format|
      if @lunch.update(lunch_params)
        format.html { redirect_to @lunch, notice: 'Lunch was successfully updated.' }
        format.json { render :show, status: :ok, location: @lunch }
      else
        format.html { render :edit }
        format.json { render json: @lunch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lunches/1
  # DELETE /lunches/1.json
  def destroy
    @lunch.destroy
    respond_to do |format|
      format.html { redirect_to lunches_url, notice: 'Lunch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lunch
      @lunch = Lunch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lunch_params
      params.require(:lunch).permit(:supplier, :sign_up_date_time, :creator)
    end
end

web/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

web/app/helpers/application_helper.rb
module ApplicationHelper
end

web/app/helpers/articles_helper.rb
module ArticlesHelper
end

web/app/helpers/comments_helper.rb
module CommentsHelper
end

web/app/helpers/lunch_items_helper.rb
module LunchItemsHelper
end

web/app/helpers/lunches_helper.rb
module LunchesHelper
end

web/app/helpers/welcome_helper.rb
module WelcomeHelper
end

web/app/views/bloggs/_form.html.erb
<%= form_for @article do |f| %>

    <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@article.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @article.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>

    <p>
      <%= f.submit %>
    </p>

<% end %>

web/app/views/bloggs/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Back', bloggs_path %>

web/app/views/bloggs/index.html.erb
<h1>Listing articles</h1>

<%= link_to 'New article', new_blogg_path %>


<% if flash[:error] %>
    <p class="notice"><%= flash[:error] %></p>
<% end %>

<% if user_signed_in? %>
    <li>
      <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
    </li>
<% else %>
    <li>
      <%= link_to('Login', new_user_session_path)  %>
    </li>
<% end %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>

  <% @articles.each do |blogg| %>
      <tr>
        <td><%= blogg.title %></td>
        <td><%= blogg.text %></td>
        <td><%= link_to 'Show', blogg_path(blogg) %></td>
        <td><%= link_to 'Edit', edit_blogg_path(blogg) %></td>
        <td><%= link_to 'Destroy', blogg_path(blogg),
                        method: :delete,
                        data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>

</table>

web/app/views/bloggs/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', bloggs_path %>

web/app/views/bloggs/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>


<h2>Add a comment:</h2>
<%= render 'comments/form' %>


<%= link_to 'Back', bloggs_path %>
<%= link_to 'Edit', edit_blogg_path(@article) %>

web/app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.blogg, comment],
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
</p>

web/app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
    <p>
      <%= f.label :commenter %><br>
      <%= f.text_field :commenter %>
    </p>
    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'bootstrap' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</head>
<body>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

web/app/views/lunch_items/_form.html.erb
<%= form_for(@lunch_item) do |f| %>
  <% if @lunch_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lunch_item.errors.count, "error") %> prohibited this lunch_item from being saved:</h2>

      <ul>
      <% @lunch_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :vegetarian %><br>
    <%= f.check_box :vegetarian %>
  </div>
  <div class="field">
    <%= f.label :lunch_id %><br>
    <%= f.number_field :lunch_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

web/app/views/lunch_items/edit.html.erb
<h1>Editing Lunch Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @lunch_item %> |
<%= link_to 'Back', lunch_items_path %>

web/app/views/lunch_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lunch Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Vegetarian</th>
      <th>Lunch</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lunch_items.each do |lunch_item| %>
      <tr>
        <td><%= lunch_item.name %></td>
        <td><%= lunch_item.vegetarian %></td>
        <td><%= lunch_item.lunch_id %></td>
        <td><%= link_to 'Show', lunch_item %></td>
        <td><%= link_to 'Edit', edit_lunch_item_path(lunch_item) %></td>
        <td><%= link_to 'Destroy', lunch_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lunch item', new_lunch_item_path %>

web/app/views/lunch_items/new.html.erb
<h1>New Lunch Item</h1>

<%= render 'form' %>

<%= link_to 'Back', lunch_items_path %>

web/app/views/lunch_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lunch_item.name %>
</p>

<p>
  <strong>Vegetarian:</strong>
  <%= @lunch_item.vegetarian %>
</p>

<p>
  <strong>Lunch:</strong>
  <%= @lunch_item.lunch_id %>
</p>

<%= link_to 'Edit', edit_lunch_item_path(@lunch_item) %> |
<%= link_to 'Back', lunch_items_path %>

web/app/views/lunches/_form.html.erb
<%= form_for(@lunch) do |f| %>
  <% if @lunch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lunch.errors.count, "error") %> prohibited this lunch from being saved:</h2>

      <ul>
      <% @lunch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :supplier %><br>
    <%= f.text_field :supplier %>
  </div>
  <div class="field">
    <%= f.label :sign_up_date_time %><br>
    <%= f.datetime_select :sign_up_date_time %>
  </div>
  <div class="field">
    <%= f.label :creator %><br>
    <%= f.text_field :creator %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

web/app/views/lunches/edit.html.erb
<h1>Editing Lunch</h1>

<%= render 'form' %>

<%= link_to 'Show', @lunch %> |
<%= link_to 'Back', lunches_path %>

web/app/views/lunches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lunches</h1>

<table>
  <thead>
    <tr>
      <th>Supplier</th>
      <th>Sign up date time</th>
      <th>Creator</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lunches.each do |lunch| %>
      <tr>
        <td><%= lunch.supplier %></td>
        <td><%= lunch.sign_up_date_time %></td>
        <td><%= lunch.creator %></td>
        <td><%= link_to 'Show', lunch %></td>
        <td><%= link_to 'Edit', edit_lunch_path(lunch) %></td>
        <td><%= link_to 'Destroy', lunch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lunch', new_lunch_path %>

web/app/views/lunches/new.html.erb
<h1>New Lunch</h1>

<%= render 'form' %>

<%= link_to 'Back', lunches_path %>

web/app/views/lunches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Supplier:</strong>
  <%= @lunch.supplier %>
</p>

<p>
  <strong>Sign up date time:</strong>
  <%= @lunch.sign_up_date_time %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @lunch.creator %>
</p>

<%= link_to 'Edit', edit_lunch_path(@lunch) %> |
<%= link_to 'Back', lunches_path %>

web/app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: :bloggs %>